CREATE TABLE PRODUCT(
	"NO" NUMBER PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	PRICE NUMBER,
	P_DATE DATE
)
-- 컬럼명 변경
ALTER TABLE PRODUCT RENAME COLUMN "NO" TO NUM;
-- 컬럼타입 변경
ALTER TABLE PRODUCT MODIFY NAME VARCHAR2(200);
-- 컬럼추가
ALTER TABLE PRODUCT ADD AGE NUMBER;
-- 컬럼삭제
ALTER TABLE PRODUCT DROP COLUMN AGE;
-- 테이블이 이미 생성된 후 제약조건 추가
ALTER TABLE PRODUCT ADD CONSTRAINT PR_KEY PRIMARY KEY NAME;
-- 제약조건 삭제
ALTER TABLE PRODUCT DROP CONSTRAINT PR_KEY;

CREATE TABLE TBL_STUDENT(
	ID NUMBER,
	NAME VARCHAR2(100),
	MAJOR VARCHAR2(100),
	GENDER CHAR(1) DEFAULT 'M' NOT NULL CONSTRAINT BAN_CHAR CHECK(GENDER = 'M' OR GENDER = 'W');
	BIRTH DATE CONSTRAINT BAN_DATE CHECK(BIRTH >= TO_DATE('1980-01-01','YYYY-MM-DD')),
	CONSTRAINT STD_PK PRIMARY KEY(ID)	
);

CREATE TABLE "USER"(
	ID VARCHAR2(100) PRIMARY KEY,
	PW VARCHAR2(100),
	NAME VARCHAR2(50),
	ADDRESS VARCHAR2(100),
	EMAIL VARCHAR2(50),
	BIRTH DATE
)

CREATE TABLE PRODUCT(
	PRODUCT_NUM NUMBER PRIMARY KEY,
	PRDOUCT_NAME VARCHAR2(300),
	PRODUCT_PRICE NUMBER,
	PRODUCT_COUNT NUMBER
)

--주문테이블
CREATE TABLE "ORDER"(
	ORDER_NUM NUMBER PRIMARY KEY, -- 주문번호
	ORDER_DATE DATE,
	ID VARCHAR2(100),
	PRODUCT_NUM NUMBER,
	-- 외래키 설정(FOREIGN KEY)
	CONSTRAINT USER_FK FOREIGN KEY(ID) REFERENCES "USER"(ID);
	CONSTRAINT PRODUCT_FK FOREIGN KEY(PRODUCT_NUM) REFERENCES PRODUCT(PRODUCT_NUM);
)












